<?xml version="1.0"?>

<robot name="wheel" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="rplidar"
    params="
      name
      parent
      base_length
      base_height
      radius
      length">

    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <material name="dark_gray">
            <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-5" ixy="0.0" ixz="0.0"
                iyy="1e-5" iyz="0.0"
                izz="1e-5"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_link"/>
      <origin xyz="${base_length/2 + radius} 0 ${base_height/2 + length/2}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  
</robot>
