// Generated by gencpp from file robot_control/i2c_data.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_I2C_DATA_H
#define ROBOT_CONTROL_MESSAGE_I2C_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct i2c_data_
{
  typedef i2c_data_<ContainerAllocator> Type;

  i2c_data_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , timestamp(0.0)  {
    }
  i2c_data_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , timestamp(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::robot_control::i2c_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::i2c_data_<ContainerAllocator> const> ConstPtr;

}; // struct i2c_data_

typedef ::robot_control::i2c_data_<std::allocator<void> > i2c_data;

typedef boost::shared_ptr< ::robot_control::i2c_data > i2c_dataPtr;
typedef boost::shared_ptr< ::robot_control::i2c_data const> i2c_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::i2c_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::i2c_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control::i2c_data_<ContainerAllocator1> & lhs, const ::robot_control::i2c_data_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control::i2c_data_<ContainerAllocator1> & lhs, const ::robot_control::i2c_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_control::i2c_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::i2c_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::i2c_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::i2c_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::i2c_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::i2c_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::i2c_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14eb7bbd6a88245711aff1553f6d4423";
  }

  static const char* value(const ::robot_control::i2c_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14eb7bbd6a882457ULL;
  static const uint64_t static_value2 = 0x11aff1553f6d4423ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::i2c_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/i2c_data";
  }

  static const char* value(const ::robot_control::i2c_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::i2c_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# i2c_data.msg\n"
"float64 x\n"
"float64 y\n"
"float64 z \n"
"float64 timestamp\n"
;
  }

  static const char* value(const ::robot_control::i2c_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::i2c_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct i2c_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::i2c_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::i2c_data_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_I2C_DATA_H
