// Generated by gencpp from file robot_control/velocity_data.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_VELOCITY_DATA_H
#define ROBOT_CONTROL_MESSAGE_VELOCITY_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct velocity_data_
{
  typedef velocity_data_<ContainerAllocator> Type;

  velocity_data_()
    : angular_speed_left(0.0)
    , angular_speed_right(0.0)
    , servo_angle(0.0)  {
    }
  velocity_data_(const ContainerAllocator& _alloc)
    : angular_speed_left(0.0)
    , angular_speed_right(0.0)
    , servo_angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angular_speed_left_type;
  _angular_speed_left_type angular_speed_left;

   typedef float _angular_speed_right_type;
  _angular_speed_right_type angular_speed_right;

   typedef float _servo_angle_type;
  _servo_angle_type servo_angle;





  typedef boost::shared_ptr< ::robot_control::velocity_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::velocity_data_<ContainerAllocator> const> ConstPtr;

}; // struct velocity_data_

typedef ::robot_control::velocity_data_<std::allocator<void> > velocity_data;

typedef boost::shared_ptr< ::robot_control::velocity_data > velocity_dataPtr;
typedef boost::shared_ptr< ::robot_control::velocity_data const> velocity_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::velocity_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::velocity_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control::velocity_data_<ContainerAllocator1> & lhs, const ::robot_control::velocity_data_<ContainerAllocator2> & rhs)
{
  return lhs.angular_speed_left == rhs.angular_speed_left &&
    lhs.angular_speed_right == rhs.angular_speed_right &&
    lhs.servo_angle == rhs.servo_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control::velocity_data_<ContainerAllocator1> & lhs, const ::robot_control::velocity_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_control::velocity_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::velocity_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::velocity_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::velocity_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::velocity_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::velocity_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::velocity_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e294170f2d297bc948c772795931b47a";
  }

  static const char* value(const ::robot_control::velocity_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe294170f2d297bc9ULL;
  static const uint64_t static_value2 = 0x48c772795931b47aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::velocity_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/velocity_data";
  }

  static const char* value(const ::robot_control::velocity_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::velocity_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# velocity_data.msg\n"
"float32 angular_speed_left\n"
"float32 angular_speed_right\n"
"float32 servo_angle\n"
;
  }

  static const char* value(const ::robot_control::velocity_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::velocity_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular_speed_left);
      stream.next(m.angular_speed_right);
      stream.next(m.servo_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocity_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::velocity_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::velocity_data_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "angular_speed_left: ";
    Printer<float>::stream(s, indent + "  ", v.angular_speed_left);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_speed_right: ";
    Printer<float>::stream(s, indent + "  ", v.angular_speed_right);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "servo_angle: ";
    Printer<float>::stream(s, indent + "  ", v.servo_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_VELOCITY_DATA_H
