goals:

    #Primeiro Goal
  - x: 1.4
    y: 0.0
    theta: 0.0
    rampa: false
    #Segundo Goal
  - x: 2.0
    y: 1.5
    theta: 0.0
    rampa: true
    #Rampa
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false
    #Terceiro Goal
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false
    #Objetivo 1
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false
    #Quarto Goal
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false
    #Quinto Goal
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false
    #Objetivo 2
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false
    #Sexto Goal (tentando ajustar para curva)
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false
    #Sexto Goal
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false
    #Sétimo Goal
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false
    #Objetivo Final
  - x: 2.0
    y: 1.0
    theta: 1.57  # 90 degrees
    rampa: false